import { ASTNode, type ExprVisitor, type StmtVisitor, LiteralExpr, BinaryExpr, UnaryExpr, IdentifierExpr, GroupingExpr, CallExpr, AssignExpr, AddressOfExpr, DereferenceExpr, ExpressionStmt, BlockStmt, LetStmt, ConstStmt, IfStmt, WhileStmt, ReturnStmt, FunctionDeclaration } from '../ast.js';
import { LLVMIRHelper } from './llvm_ir_helpers.js';
import { Parser } from '../parser/index.js';
import { BuiltinFunctions } from './builtins.js';
import type { LLVMModuleRef, LLVMBuilderRef, LLVMValueRef, LLVMTypeRef } from '../llvm/index.js';
export type IRValue = {
    value: LLVMValueRef;
    type: LLVMTypeRef;
    classInstancePtr?: LLVMValueRef;
    classInstancePtrType?: LLVMTypeRef;
    ptr?: LLVMValueRef;
    ptrType?: LLVMTypeRef;
    address?: LLVMValueRef;
};
type SymbolEntry = {
    llvmType: LLVMTypeRef;
    ptr: LLVMValueRef;
    isPointer: boolean;
    definedInScopeDepth: number;
};
declare class Scope {
    parent: Scope | null;
    depth: number;
    private symbols;
    constructor(parent?: Scope | null, depth?: number);
    define(name: string, entry: SymbolEntry): boolean;
    find(name: string): SymbolEntry | null;
}
export declare class IRGenerator implements ExprVisitor<IRValue>, StmtVisitor<void> {
    builder: LLVMBuilderRef;
    module: LLVMModuleRef;
    indentLevel: number;
    llvmHelper: LLVMIRHelper;
    builtins: BuiltinFunctions;
    private globalScope;
    currentScope: Scope;
    private currentFunction;
    private labelCounter;
    private classDefinitions;
    private declaredSymbols;
    private generatedFunctions;
    private sretPointer;
    private parser;
    private mangleStdLib;
    private sourceFilePath;
    private debug;
    private pass;
    private objectLiteralCounter;
    private objectLiteralExpectedStructType;
    private arrayLiteralExpectedStructType;
    private heapGlobalsEmitted;
    private lowLevelRuntimeEmitted;
    private moduleObjects;
    private hoistedDefinitions;
    private hoistedFunctions;
    platform: IPlatform;
    private emittedArrayStructs;
    getModule(): LLVMModuleRef;
    private splitStructFields;
    private emitHoisted;
    private hoistFunctionDefinition;
    constructor(platform: IPlatform, parser: Parser, mangleStdLib?: boolean, sourceFilePath?: string, debug?: boolean);
    getGlobalSymbol(name: string): SymbolEntry | null;
    generate(nodes: ASTNode[]): string;
    private emitGlobalDefinitions;
    private enterScope;
    private exitScope;
    getNewLabel(prefix: string): string;
    emit(ir: string, indent?: boolean): void;
    ensureSyscallDecl(): void;
    ensureHeapGlobals(): void;
    private emitHeapGlobals;
    private emitLowLevelRuntime;
    ensureI64(irValue: IRValue): LLVMValueRef;
    private getFunctionKey;
    private emitLangItemStructs;
    private buildModuleObject;
    private concatStrings;
    ensureStringPointer(val: IRValue): IRValue | null;
    private ensureArrayPointer;
    coerceValue(value: IRValue, targetType: string): IRValue;
    visitAddressOfExpr(expr: AddressOfExpr): IRValue;
    visitDereferenceExpr(expr: DereferenceExpr): IRValue;
    visitLiteralExpr(expr: LiteralExpr): IRValue;
    visitIdentifierExpr(expr: IdentifierExpr): IRValue;
    visitBinaryExpr(expr: BinaryExpr): IRValue;
    visitUnaryExpr(expr: UnaryExpr): IRValue;
    visitGroupingExpr(expr: GroupingExpr): IRValue;
    visitCallExpr(expr: CallExpr): IRValue;
    visitAssignExpr(expr: AssignExpr): IRValue;
    visitExpressionStmt(stmt: ExpressionStmt): void;
    visitLetStmt(stmt: LetStmt): void;
    visitConstStmt(stmt: ConstStmt): void;
    visitGlobalLetStmt(stmt: LetStmt): void;
    visitLocalLetStmt(stmt: LetStmt): void;
    visitBlockStmt(stmt: BlockStmt): void;
    visitIfStmt(stmt: IfStmt): void;
    visitWhileStmt(stmt: WhileStmt): void;
    visitReturnStmt(stmt: ReturnStmt): void;
    visitFunctionDeclaration(decl: FunctionDeclaration): void;
    declareFunctionSymbol(decl: FunctionDeclaration): void;
    emitFunctionDefinition(decl: FunctionDeclaration): void;
    const paramsString: any;
}
export {};
//# sourceMappingURL=ir_generator.d.ts.map